---
- name: Update and Upgrade Boinc Clients
  hosts: boinc  # Replace with the target host or group of hosts where you want to run the updates.
  become: yes  # To run commands with sudo privileges, if required.

  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"  # This condition ensures it only runs on Debian-based systems.

    - name: Upgrade packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      when: ansible_os_family == "Debian"  # This condition ensures it only runs on Debian-based systems.
